# coding: utf-8
from sqlalchemy import Column, DateTime, String
from sqlalchemy.dialects.mysql import INTEGER, VARCHAR
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


class VideoContentMedia(Base):
    __tablename__ = 'video_content_media'

    id = Column(INTEGER(11), primary_key=True)
    media_id = Column(INTEGER(8))
    os_key = Column(VARCHAR(20))
    name = Column(VARCHAR(50))
    source_type = Column(INTEGER(2))
    icon = Column(VARCHAR(255))
    cover = Column(VARCHAR(255))
    source_ids = Column(VARCHAR(255))
    third_id = Column(VARCHAR(255))
    create_time = Column(VARCHAR(64))
    status = Column(INTEGER(2))
    video_describe = Column(VARCHAR(255))
    video_ext = Column(VARCHAR(2024))
    video_province = Column(VARCHAR(64))
    video_city = Column(VARCHAR(64))
    video_area = Column(VARCHAR(64))
    video_sex = Column(VARCHAR(64))
    video_age = Column(VARCHAR(32))
    video_email = Column(VARCHAR(80))
    video_country = Column(VARCHAR(64))
    video_address = Column(VARCHAR(255))
    video_birth = Column(VARCHAR(64))
    video_position_lng = Column(VARCHAR(64))
    position_lat = Column(VARCHAR(64))
    media_num = Column(VARCHAR(64))
    latitude = Column(VARCHAR(64))
    longitude = Column(VARCHAR(64))
    update_time = Column(DateTime)
    sign_time = Column(VARCHAR(64))
    able_status = Column(INTEGER(2))
    speech_status = Column(INTEGER(2))
    media_mark = Column(INTEGER(2))


class VideoContentMediaBak(Base):
    __tablename__ = 'video_content_media_bak'

    id = Column(INTEGER(11), primary_key=True)
    media_id = Column(INTEGER(8))
    os_key = Column(VARCHAR(20))
    name = Column(VARCHAR(50))
    source_type = Column(INTEGER(2))
    icon = Column(VARCHAR(255))
    cover = Column(VARCHAR(255))
    source_ids = Column(VARCHAR(255))
    third_id = Column(VARCHAR(255))
    create_time = Column(VARCHAR(64))
    status = Column(INTEGER(2))
    describe = Column(VARCHAR(255))
    ext = Column(VARCHAR(255))
    province = Column(VARCHAR(64))
    city = Column(VARCHAR(64))
    area = Column(VARCHAR(64))
    sex = Column(VARCHAR(64))
    age = Column(VARCHAR(32))
    email = Column(VARCHAR(80))
    country = Column(String(64))
    address = Column(String(255))
    birth = Column(String(64))
    position_lng = Column(String(64))
    position_lat = Column(String(64))
    media_num = Column(String(64))
    latitude = Column(String(64))
    longitude = Column(String(64))
    update_time = Column(DateTime)
    sign_time = Column(String(64))
    able_status = Column(INTEGER(2))
    speech_status = Column(INTEGER(2))
    media_mark = Column(INTEGER(2))


class VideoInfo(Base):
    __tablename__ = 'video_info'

    id = Column(INTEGER(11), primary_key=True)
    video_id = Column(String(64))
    publish_time = Column(String(64))
    update_time = Column(DateTime)
    play_num = Column(INTEGER(11))
    praise_num = Column(INTEGER(11))
    comments_num = Column(INTEGER(11))
    address = Column(String(128))
    city = Column(String(64))
    city_code = Column(String(64))
    content = Column(String(2048))
    country = Column(String(64))
    country_code = Column(String(64))
    cover = Column(String(255))
    creator = Column(String(64))
    district = Column(String(64))
    district_code = Column(String(64))
    iid = Column(String(64))
    imgs = Column(String(1024))
    insert_time = Column(String(64))
    latitude = Column(String(255))
    longitude = Column(String(255))
    media_desc = Column(String(255))
    media_icon = Column(String(255))
    media_id = Column(String(64))
    media_name = Column(String(64))
    media_type = Column(String(64))
    mid = Column(String(64))
    province = Column(String(64))
    province_code = Column(String(64))
    pub_time = Column(String(64))
    share_count = Column(String(64))
    summary = Column(String(1024))
    title = Column(String(64))
    top_type = Column(String(64))
    topic = Column(String(64))
    type = Column(String(64))
    unq_id = Column(String(64))
    wifi = Column(String(64))
    network_type = Column(String(64))
    platform = Column(String(64))
    video_time = Column(String(64))
    manufacturer = Column(String(64))
    is_login_id = Column(String(64))
    channel_id = Column(String(64))
    video_tag = Column(String(64))
    screen_width = Column(String(64))
    screen_height = Column(String(64))
    model = Column(String(64))
    is_first_day = Column(String(64))
    topic_info = Column(String(2048))
    item_info = Column(String(2048))


class VideoInfoBak(Base):
    __tablename__ = 'video_info-bak'

    id = Column(INTEGER(11), primary_key=True)
    video_id = Column(String(64))
    publish_time = Column(String(64))
    update_time = Column(DateTime)
    play_num = Column(INTEGER(11))
    praise_num = Column(INTEGER(11))
    comments_num = Column(INTEGER(11))
    address = Column(String(128))
    city = Column(String(64))
    city_code = Column(String(64))
    content = Column(String(255))
    country = Column(String(64))
    country_code = Column(String(64))
    cover = Column(String(255))
    creator = Column(String(64))
    district = Column(String(64))
    district_code = Column(String(64))
    iid = Column(String(64))
    imgs = Column(String(255))
    insert_time = Column(String(64))
    latitude = Column(String(255))
    longitude = Column(String(255))
    media_desc = Column(String(255))
    media_icon = Column(String(255))
    media_id = Column(String(64))
    media_name = Column(String(64))
    media_type = Column(String(64))
    mid = Column(String(64))
    province = Column(String(64))
    province_code = Column(String(64))
    pub_time = Column(String(64))
    share_count = Column(String(64))
    summary = Column(String(64))
    title = Column(String(64))
    top_type = Column(String(64))
    topic = Column(String(64))
    type = Column(String(64))
    unq_id = Column(String(64))
    wifi = Column(String(64))
    network_type = Column(String(64))
    platform = Column(String(64))
    video_time = Column(String(64))
    manufacturer = Column(String(64))
    is_login_id = Column(String(64))
    channel_id = Column(String(64))
    video_tag = Column(String(64))
    screen_width = Column(String(64))
    screen_height = Column(String(64))
    model = Column(String(64))
    is_first_day = Column(String(64))


class VideoUser(Base):
    __tablename__ = 'video_user'

    id = Column(INTEGER(11), primary_key=True)
    media_id = Column(String(64))
    screen_height = Column(String(64))
    screen_width = Column(String(64))
    is_first_day = Column(String(64))
    manufacturer = Column(String(255))
    wifi = Column(String(255))
    model = Column(String(255))
    network_type = Column(String(255))
    os = Column(String(255))
    update_time = Column(DateTime)